[package]
name = "cmm-desktop"
version = "0.1.0"
edition = "2021"
description = "Class Material Manager Windows Desktop PoC"

[build-dependencies]
tauri-build = { version = "=2.7.1", features = [] }

[dependencies]
tauri = { version = "=2.12.1", features = [] }

[features]
custom-protocol = ["tauri/custom-protocol"]
