-- data/*.json (index/relations/learning/comparisons/study-guides) 를 담는 5개 핵심 테이블.
--
-- 이 파일은 사후 복원본입니다. 실제로는 2026-08-25~26 사이 Supabase 콘솔(SQL 편집기)에서
-- 직접 실행되어 이미 원격에 적용돼 있었고(마이그레이션 이력에는 `create_learning_data_schema`
-- 로 이름만 남아 있음), 로컬 저장소에는 그 SQL 파일 자체가 커밋되지 않았습니다.
-- 2026-08-27, 실제 운영 Supabase 프로젝트의 현재 스키마(정보스키마·pg_constraint·pg_indexes·
-- pg_policies를 직접 조회)를 그대로 옮겨 적어 fresh clone에서도 동일한 스키마를 재현할 수
-- 있도록 복원했습니다. 이 마이그레이션을 다시 실행하지 마세요 — 원격에는 이미 적용되어 있고,
-- 로컬 이력만 채워 넣기 위한 기록입니다.
--
-- 원본 산출물과의 대응, 컬럼 의미, 원본 본문 미저장 원칙 등은 PROJECT_CONTEXT.md의
-- "Supabase DB 이관" 절과 src/sync/*.ts 를 참고하세요.

-- ── material_metadata: index.json 의 자료 메타데이터 (본문 아님) ──────────
create table if not exists public.material_metadata (
  source_id text primary key,
  kind text not null,
  title text not null,
  subject text,
  mime_type text,
  format text,
  source_url text,
  file_path text,
  content_hash text,
  source_modified_at timestamptz,
  collected_at timestamptz,
  source_updated_at timestamptz,
  occurrences jsonb not null default '[]'::jsonb,
  extra jsonb not null default '{}'::jsonb,
  synced_at timestamptz not null default now()
);

create index if not exists material_metadata_kind_idx on public.material_metadata (kind);
create index if not exists material_metadata_subject_idx on public.material_metadata (subject);
create index if not exists material_metadata_updated_idx on public.material_metadata (source_updated_at desc);

alter table public.material_metadata enable row level security;

create policy "authenticated users can read material metadata"
  on public.material_metadata for select
  to authenticated
  using (true);

-- ── relations: 설명자료 ↔ 실습zip 연결 근거 (relations.json) ──────────────
create table if not exists public.relations (
  id bigint generated by default as identity primary key,
  material_id text not null references public.material_metadata (source_id) on delete cascade,
  zip_id text not null references public.material_metadata (source_id) on delete cascade,
  subject text,
  confidence text not null check (confidence in ('high', 'medium', 'low')),
  score numeric,
  reasons jsonb not null default '[]'::jsonb,
  source_files jsonb not null default '[]'::jsonb,
  generated_at timestamptz,
  synced_at timestamptz not null default now(),
  unique (material_id, zip_id)
);

create index if not exists relations_material_idx on public.relations (material_id);
create index if not exists relations_zip_idx on public.relations (zip_id);
create index if not exists relations_confidence_idx on public.relations (confidence);

alter table public.relations enable row level security;

create policy "authenticated users can read relations"
  on public.relations for select
  to authenticated
  using (true);

-- ── learning_documents: 통합 학습자료 (learning.json, 실습 코드 원문 제외) ──
create table if not exists public.learning_documents (
  material_id text primary key references public.material_metadata (source_id) on delete cascade,
  subject text,
  title text,
  practice_relations jsonb not null default '[]'::jsonb,
  source_files jsonb not null default '[]'::jsonb,
  official_docs jsonb not null default '[]'::jsonb,
  content jsonb not null default '{}'::jsonb,
  generated_at timestamptz,
  synced_at timestamptz not null default now()
);

create index if not exists learning_documents_subject_idx on public.learning_documents (subject);

alter table public.learning_documents enable row level security;

create policy "authenticated users can read learning documents"
  on public.learning_documents for select
  to authenticated
  using (true);

-- ── comparisons: 수업 당시 방식 ↔ 공식 문서 점검 결과 (comparisons.json) ───
create table if not exists public.comparisons (
  id text primary key,
  material_id text references public.material_metadata (source_id) on delete cascade,
  subject text,
  technology text,
  status text,
  change_type text,
  severity text,
  reason text,
  needs_review boolean not null default false,
  evidence jsonb not null default '[]'::jsonb,
  official jsonb not null default '{}'::jsonb,
  details jsonb not null default '{}'::jsonb,
  checked_at timestamptz,
  generated_at timestamptz,
  synced_at timestamptz not null default now()
);

create index if not exists comparisons_material_idx on public.comparisons (material_id);
create index if not exists comparisons_subject_idx on public.comparisons (subject);
create index if not exists comparisons_status_idx on public.comparisons (status);
create index if not exists comparisons_severity_idx on public.comparisons (severity);
create index if not exists comparisons_review_idx on public.comparisons (needs_review) where needs_review = true;

alter table public.comparisons enable row level security;

create policy "authenticated users can read comparisons"
  on public.comparisons for select
  to authenticated
  using (true);

-- ── study_guides: 복습 우선순위·설명 (study-guides.json 의 guides[]) ──────
create table if not exists public.study_guides (
  comparison_id text primary key references public.comparisons (id) on delete cascade,
  material_id text references public.material_metadata (source_id) on delete cascade,
  subject text,
  learning_priority text,
  explanation text,
  recommended_alternative text,
  study_point text,
  details jsonb not null default '{}'::jsonb,
  generated_at timestamptz,
  synced_at timestamptz not null default now()
);

create index if not exists study_guides_material_idx on public.study_guides (material_id);
create index if not exists study_guides_subject_idx on public.study_guides (subject);
create index if not exists study_guides_priority_idx on public.study_guides (learning_priority);

alter table public.study_guides enable row level security;

create policy "authenticated users can read study guides"
  on public.study_guides for select
  to authenticated
  using (true);
